const test=require('node:test'),assert=require('node:assert/strict');
const {parseCagListing,parseCagDetail}=require('../lib/ingestion/connectors/cagReportsConnector');
const title='Report No. 2 of 2026 - State Finances Nagaland';
const listing=`<div class="AuditReportlisting"><div class="dateFirst"><span class="dtn">03 September 2026</span><div class="reportType">Financial</div></div><div class="reportIcon"><h5>Nagaland</h5></div><div class="reportDetail"><a href="/en/audit-report/details/126325">${title}</a></div><div class="sectorDetail"><div>Sector:</div><div>Finance</div></div></div><a href="?page=2">&gt;&gt;</a>`;
const file='https://cag.gov.in/uploads/download_audit_report/2026/full.pdf';
const detail=`<div class="auditDetailColl"><h3 class="singTitle">${title}</h3><ul class="guidelinesList"><li><a href="${file}">${title}</a><a href="${file}">Download</a></li><li><a href="https://cag.gov.in/uploads/download_audit_report/2026/chapter.pdf">Chapter-I Overview</a></li><li><a href="https://cag.gov.in/uploads/download_audit_report/2026/cover.pdf">Outer Cover</a></li></ul></div><a href="https://cag.gov.in/uploads/download_audit_report/2026/unrelated.pdf">Unrelated</a>`;
test('CAG extracts explicit date, report identity, jurisdiction and observed next URL',()=>{const result=parseCagListing(listing,'https://cag.gov.in/en/audit-report');assert.equal(result.records[0].publicationDate,'2026-09-03');assert.equal(result.records[0].metadata.reportNumber,'2');assert.equal(result.records[0].jurisdiction,'Nagaland');assert.equal(result.nextUrl,'https://cag.gov.in/en/audit-report?page=2');});
test('CAG only associates explicit report/chapter links and keeps one full report',()=>{const parent=parseCagListing(listing,'https://cag.gov.in/en/audit-report').records[0];const record=parseCagDetail(detail,parent);assert.equal(record.pdfUrl,file);assert.equal(record.resources.length,2);assert.equal(record.sourceRecordId,parent.sourceRecordId);assert.throws(()=>parseCagDetail(detail.replace(title,'A different report'),parent),/title/);assert.throws(()=>parseCagDetail(detail.replaceAll(file,'https://cag.gov.in.attacker.test/full.pdf'),parent),/missing or ambiguous/);});
test('CAG unknown dates remain unknown; no date is borrowed from title years',()=>{assert.equal(parseCagListing(listing.replace('03 September 2026',''),'https://cag.gov.in/en/audit-report').records[0].publicationDate,null);});
